name: Publish @doist/react-compiler-tracker package

on:
    push:
        tags:
            - 'v*'
    # triggered by `release-please.yml`
    workflow_dispatch:

permissions:
    contents: read
    packages: write

jobs:
    publish:
        runs-on: ubuntu-latest
        timeout-minutes: 10

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Prepare Node.js environment for GitHub Packages registry
              uses: actions/setup-node@v6
              with:
                  cache: npm
                  node-version-file: .node-version
                  registry-url: https://npm.pkg.github.com/
                  scope: '@doist'

            - name: Ensure npm 11.5.1 or later is installed
              run: npm install -g npm@latest

            - name: Install project npm dependencies
              run: npm ci

            - run: npm run check
            - run: npm run test
            - run: npm run build

            - name: Publish package to GitHub Packages registry
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
